### ISSUE TITLE
Help Me with Laravel - Socialite

### ISSUE THREAD

**Issue by webdev522** [vickris/lara-social#1]
Hello, Andela.

I want to build a social login laravel module.
But during the following your tutorial "Laravel Social Authentication with Socialite" on scotch.io,
I have installation errors.

composer require laravel/socialite

then error shows as follow.

=======================================================
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - laravel/socialite v3.0.0 requires illuminate/support ~5.4 -> satisfiable by illuminate/support[v5.4.0, v5.4.9].
    - laravel/socialite v3.0.2 requires illuminate/support ~5.4 -> satisfiable by illuminate/support[v5.4.0, v5.4.9].
    - laravel/socialite v3.0.3 requires illuminate/support ~5.4 -> satisfiable by illuminate/support[v5.4.0, v5.4.9].
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].
    - Installation request for laravel/socialite ^3.0 -> satisfiable by laravel/socialite[v3.0.0, v3.0.2, v3.0.3].
===================================================================

My laravel version is 5.2.* (composer create-project laravel/laravel lara-social "5.2.*")
I think laravel/socialite[v3.0.0, v3.0.2, v3.0.3] doesn't match laravel 5.2.*.

Please help me complete my social authentication project.

Best Regards.
webdev522.

Installation failed, reverting ./composer.json to its original content.

**Comment by vickris** [comment]
Try doing a composer update then require socialite. Let me know how it goes

**Comment by webdev522** [comment]
Yes, it goes well.

Thank you for your help.

Best Regards.

**Comment by vickris** [comment]
You welcome
